[package]
name = "khalzam"
version = "0.2.1"
authors = ["kisasexypantera94 <green.grinya@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Simple audio recognition library, port of khalzam-go"
repository = "https://github.com/kisasexypantera94/khalzam-rs"

[dependencies]
postgres = "0.15"
minimp3 = "0.3.2"
rustfft = "3.0.0"