[package]
name = "khalzam"
version = "0.1.0"
authors = ["kisasexypantera94 <green.grinya@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Simple audio recognition library, port of khalzam-go"

[dependencies]
postgres = "0.15"
minimp3 = "0.3.2"
rustfft = "3.0.0"